
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[374] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       74,   72,   69,   71,   71,   70,   19,   56,   45,   17,
       72,   13,   23,    5,   21,    6,   16,   72,    7,   47,
       47,   25,   15,    4,   10,   45,   45,   14,   24,   29,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   11,   72,   22,
       55,   54,   54,   55,   62,   61,   61,   57,   62,   68,
       67,   67,   63,   68,   50,   49,   49,   71,   18,   45,
        3,    1,   26,   46,    0,    0,   51,   48,   46,    0,
        0,    0,   47,    0,   27,   12,    8,    9,   28,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,    1,   45,   45,   45,   45,   45,
       45,   45,   45,   35,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   20,   54,   53,    0,   52,   61,   58,
       60,   59,   67,   64,   65,   66,    0,   46,    0,   46,
        0,    0,   46,    0,   47,   45,   45,   45,   46,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,    1,   45,   45,
       45,   36,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,    0,   46,    0,    0,    0,    0,   46,
       46,   46,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   34,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,    2,   43,
       45,   45,   46,   46,    0,   46,    0,    0,   46,   46,
       46,   45,   45,   45,   45,   45,   45,   31,   45,   45,
       45,   45,    1,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,    1,   45,   45,

       44,   46,   46,    0,   46,   46,   45,   42,    1,   45,
       45,   45,   45,   33,   45,   45,   45,   45,   45,   45,
       45,   45,   39,   40,   41,   45,   45,   45,   45,   32,
        1,    0,   45,   30,   45,   45,   45,   45,   45,   45,
       45,   45,   45,    0,    0,   45,   45,   45,   45,   45,
       45,    0,    0,   45,   45,   45,    0,    0,   45,    0,
        0,   45,    0,    0,    0,    0,    0,    0,    0,    0,
       38,   37,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   26,   44,   45,   46,   47,
       48,   49,   26,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    4,    4,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    3,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    5,
        3,    3,    3,    3,    3,    3,    5,    3,    3,    5,
        3,    5,    3,    3,    3,    3,    3,    3,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[382] =
    {   0,
        0,    0,   59,   60,   63,   64,   72,   73,   79,   80,
      568,  569,  569,  569,  564,  569,  542,  569,    0,  569,
      554,  569,  569,  569,  549,  569,   62,   68,   72,   72,
       80,  569,   73,  539,   84,  515,   53,  569,  569,  569,
       95,   76,   73,   83,   78,   77,   97,  513,   97,  512,
       99,  100,  520,   94,  106,  510,  515,  569,  496,  569,
      569,  569,  552,  140,  569,  569,  551,  569,  152,  569,
      548,  549,  569,  131,  569,  569,  569,  569,  569,    0,
      569,  569,  569,  137,  145,  512,  569,  569,  147,  167,
      175,  177,  182,  184,  569,  569,  569,  569,  569,  498,

      499,  497,  199,  193,  496,  495,  497,  505,  491,  118,
      507,  506,  493,  499,  485,  486,  483,  483,  489,  486,
      484,  481,  478,    0,  480,  121,  481,  475,  471,  480,
      487,  132,  487,  470,  473,  128,  471,  476,  471,  134,
      172,  165,  474,  569,  569,  569,  209,  569,  569,  569,
      569,  569,  569,  569,  569,  569,  215,  217,  469,  219,
      228,  221,  234,  239,  243,  476,  471,  461,  245,  460,
      472,  465,  474,  469,  468,  469,  455,  453,  218,  468,
      466,  462,  454,  460,  447,  462,  461,    0,  447,  186,
      442,  454,  451,  448,  445,  445,  434,  435,  441,  432,

      434,  431,  439,  442,  428,  442,  427,  429,  429,  436,
      436,  438,  427,  251,  254,  261,  430,  269,  271,  273,
      275,  277,  429,  422,  429,  417,  416,  426,  420,  421,
      411,  409,  417,  406,  413,    0,  410,  417,  410,  402,
      414,  402,  416,  400,  395,  413,  412,  407,  402,  394,
      391,  399,  404,  390,  402,  396,  382,  385,    0,    0,
      383,  395,  279,  281,  283,  285,  381,  296,  300,  302,
      304,  393,  390,  384,  394,  376,  392,    0,  379,  380,
      385,  385,  377,  375,  368,  372,  378,  378,  375,  363,
      377,  376,  365,  374,  358,  367,  358,  356,  363,  362,

        0,  306,  308,  362,  310,  312,  353,    0,  384,  364,
      353,  346,  346,    0,  346,  339,  356,  357,  358,  353,
      352,  338,    0,    0,    0,  349,  340,  348,  341,  569,
      367,  336,  331,    0,  343,  333,  332,  331,  306,  294,
      294,  292,  298,  286,  265,  262,  264,  271,  270,  244,
      233,  248,  228,  216,  222,  194,  200,  229,  187,  173,
      173,  177,  160,  143,  161,  139,  114,   94,   68,   18,
      569,  569,  569,  346,  351,  356,  361,  364,  369,  374,
      378
    } ;

static const flex_int16_t yy_def[382] =
    {   0,
      373,    1,  374,  374,  375,  375,  376,  376,  377,  377,
      373,  373,  373,  373,  373,  373,  373,  373,  378,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  378,  378,  373,  373,  373,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  373,  373,  373,
      373,  373,  373,  379,  373,  373,  373,  373,  380,  373,
      373,  373,  373,  381,  373,  373,  373,  373,  373,  378,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  373,  373,  373,  379,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  378,  378,  378,  373,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  373,  373,  373,  373,  373,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  373,
      378,  373,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  373,  373,  378,  378,  378,  378,  378,
      378,  373,  373,  378,  378,  378,  373,  373,  378,  373,
      373,  378,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,    0,  373,  373,  373,  373,  373,  373,  373,
      373
    } ;

static const flex_int16_t yy_nxt[631] =
    {   0,
       12,   13,   14,   13,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   19,   19,   36,   37,   38,
       12,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   19,   49,   19,   50,   19,   51,   19,   52,   53,
       54,   55,   19,   56,   57,   19,   19,   19,   58,   59,
       60,   62,   62,   63,   63,   66,   66,   67,   67,  372,
       68,   68,   64,   64,   71,   71,   72,   72,   82,   73,
       73,   76,   76,   77,   77,   87,   83,   84,   84,   89,
       88,   90,   90,   69,   69,   95,   96,   89,   91,   93,

       93,   85,   74,   74,  101,   92,   91,   98,   99,  102,
       91,  105,   86,   94,  103,  103,  114,  110,   91,  371,
      107,  116,  108,  117,  111,  115,  106,  112,  104,  109,
      113,  119,  118,  128,  131,  135,  124,  129,  155,  120,
      370,  121,  125,  126,  122,  136,  137,  140,  138,  132,
      139,  130,  133,  147,  151,  141,   84,   84,  148,  152,
      369,  156,  202,  157,  158,  158,  160,  160,  175,  176,
       85,  191,  192,  161,  197,  157,  207,  203,   85,  198,
       85,  368,  152,  208,   89,  161,   90,   90,  367,  162,
      156,  162,  366,   91,  163,  163,  164,  164,  365,   89,

       92,   93,   93,  165,  165,   91,  209,  211,   91,  212,
       92,  152,  103,  103,  188,   94,  169,   94,  103,  103,
       91,  364,  147,  363,  210,  362,  104,  373,  188,  214,
      241,  214,  104,  242,  215,  215,  158,  158,  160,  160,
      163,  163,  219,  216,  219,  218,  361,  220,  220,  360,
       85,  359,   85,  221,  221,  216,  169,  218,  164,  164,
      169,  188,  165,  165,  158,  158,  188,  222,  232,  233,
      215,  215,   92,  263,  263,  265,   94,  265,   85,  358,
      266,  266,  357,  268,  188,  268,  356,  264,  269,  269,
      220,  220,  270,  270,  221,  221,  222,  222,  263,  263,

      264,  264,  266,  266,  302,  302,  271,  188,  222,  188,
      222,  355,  264,  354,  264,  269,  269,  353,  303,  305,
      305,  270,  270,  271,  271,  302,  302,  303,  303,  305,
      305,  306,  306,  306,  352,  271,  188,  271,  351,  303,
      350,  303,  188,  306,  349,  306,   61,   61,   61,   61,
       61,   65,   65,   65,   65,   65,   70,   70,   70,   70,
       70,   75,   75,   75,   75,   75,   80,  348,   80,  146,
      347,  146,  146,  146,  150,  150,  150,  150,  154,  346,
      154,  188,  188,  345,  344,  343,  342,  341,  340,  339,
      188,  188,  338,  337,  336,  188,  188,  188,  335,  334,

      333,  332,  331,  330,  329,  328,  188,  327,  188,  326,
      325,  324,  323,  322,  321,  320,  188,  319,  318,  188,
      317,  316,  315,  314,  313,  312,  311,  188,  310,  309,
      308,  307,  304,  301,  300,  299,  298,  297,  296,  188,
      295,  294,  188,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  188,  283,  259,  282,  281,  280,  279,
      188,  278,  188,  188,  277,  276,  275,  274,  273,  272,
      267,  262,  261,  260,  259,  258,  257,  188,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  188,
      245,  188,  244,  243,  188,  240,  239,  238,  237,  188,

      236,  235,  234,  231,  188,  230,  188,  188,  229,  228,
      227,  226,  225,  224,  223,  217,  213,  206,  205,  204,
      201,  200,  199,  196,  195,  188,  194,  193,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  174,  173,  172,  171,  170,  168,  167,  166,
      159,  153,  153,  149,  145,  144,  143,  142,  134,  127,
      123,  100,   97,   82,   81,   79,   78,  373,   11,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,

      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373
    } ;

static const flex_int16_t yy_chk[631] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    3,    4,    5,    6,    5,    6,  370,
        5,    6,    3,    4,    7,    8,    7,    8,   27,    7,
        8,    9,   10,    9,   10,   29,   27,   28,   28,   30,
       29,   30,   30,    5,    6,   33,   33,   31,   30,   31,

       31,   28,    7,    8,   37,   30,   31,   35,   35,   37,
       30,   42,   28,   31,   41,   41,   45,   44,   31,  369,
       43,   46,   43,   46,   44,   45,   42,   44,   41,   43,
       44,   47,   46,   51,   52,   54,   49,   51,   74,   47,
      368,   47,   49,   49,   47,   54,   54,   55,   54,   52,
       54,   51,   52,   64,   69,   55,   84,   84,   64,   69,
      367,   74,  136,   84,   85,   85,   89,   89,  110,  110,
       84,  126,  126,   89,  132,   84,  140,  136,   85,  132,
       89,  366,   69,  140,   90,   89,   90,   90,  365,   91,
       74,   91,  364,   90,   91,   91,   92,   92,  363,   93,

       90,   93,   93,   94,   94,   90,  141,  142,   93,  142,
       92,   69,  104,  104,  362,   93,  103,   94,  103,  103,
       93,  361,  147,  360,  141,  359,  104,  147,  141,  157,
      190,  157,  103,  190,  157,  157,  158,  158,  160,  160,
      162,  162,  161,  158,  161,  160,  358,  161,  161,  357,
      158,  356,  160,  163,  163,  158,  164,  160,  164,  164,
      165,  355,  165,  165,  169,  169,  354,  163,  179,  179,
      214,  214,  164,  215,  215,  216,  165,  216,  169,  353,
      216,  216,  352,  218,  351,  218,  350,  215,  218,  218,
      219,  219,  220,  220,  221,  221,  222,  222,  263,  263,

      264,  264,  265,  265,  266,  266,  220,  349,  221,  348,
      222,  347,  263,  346,  264,  268,  268,  345,  266,  269,
      269,  270,  270,  271,  271,  302,  302,  303,  303,  305,
      305,  306,  306,  269,  344,  270,  343,  271,  342,  302,
      341,  303,  340,  305,  339,  306,  374,  374,  374,  374,
      374,  375,  375,  375,  375,  375,  376,  376,  376,  376,
      376,  377,  377,  377,  377,  377,  378,  338,  378,  379,
      337,  379,  379,  379,  380,  380,  380,  380,  381,  336,
      381,  335,  333,  332,  331,  329,  328,  327,  326,  322,
      321,  320,  319,  318,  317,  316,  315,  313,  312,  311,

      310,  309,  307,  304,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  277,  276,  275,  274,
      273,  272,  267,  262,  261,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      217,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  189,  187,  186,  185,  184,  183,

      182,  181,  180,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  168,  167,  166,  159,  143,  139,  138,  137,
      135,  134,  133,  131,  130,  129,  128,  127,  125,  123,
      122,  121,  120,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  109,  108,  107,  106,  105,  102,  101,  100,
       86,   72,   71,   67,   63,   59,   57,   56,   53,   50,
       48,   36,   34,   25,   21,   17,   15,   11,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,

      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
    int coluna = 1;
    int linha_aux = 0;
    int coluna_aux = 0;
    char buffer[1024];

    int flag = 1;

#line 713 "lex.yy.c"

#line 715 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRLIT 2
#define ERRO_STRLIT 3
#define SINGLE_LINE_COMMENT 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 23 "jucompiler.l"


#line 939 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 374 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 569 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 25 "jucompiler.l"
{if(flag == 1){printf("RESERVED(%s)\n", yytext);}coluna += yyleng;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 27 "jucompiler.l"
{if(flag == 1){printf("BOOLLIT(%s)\n", yytext);}coluna += yyleng;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 28 "jucompiler.l"
{if(flag == 1){printf("AND\n");}coluna += yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 29 "jucompiler.l"
{if(flag == 1){printf("ASSIGN\n");}coluna += yyleng;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 30 "jucompiler.l"
{if(flag == 1){printf("STAR\n");}coluna += yyleng;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 31 "jucompiler.l"
{if(flag == 1){printf("COMMA\n");}coluna += yyleng;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 32 "jucompiler.l"
{if(flag == 1){printf("DIV\n");}coluna += yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 33 "jucompiler.l"
{if(flag == 1){printf("EQ\n");}coluna += yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 34 "jucompiler.l"
{if(flag == 1){printf("GE\n");}coluna += yyleng;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 35 "jucompiler.l"
{if(flag == 1){printf("GT\n");}coluna += yyleng;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 36 "jucompiler.l"
{if(flag == 1){printf("LBRACE\n");}coluna += yyleng;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 37 "jucompiler.l"
{if(flag == 1){printf("LE\n");}coluna += yyleng;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 38 "jucompiler.l"
{if(flag == 1){printf("LPAR\n");}coluna += yyleng;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 39 "jucompiler.l"
{if(flag == 1){printf("LSQ\n");}coluna += yyleng;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 40 "jucompiler.l"
{if(flag == 1){printf("LT\n");}coluna += yyleng;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 41 "jucompiler.l"
{if(flag == 1){printf("MINUS\n");}coluna += yyleng;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 42 "jucompiler.l"
{if(flag == 1){printf("MOD\n");}coluna += yyleng;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 43 "jucompiler.l"
{if(flag == 1){printf("NE\n");}coluna += yyleng;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{if(flag == 1){printf("NOT\n");}coluna += yyleng;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 45 "jucompiler.l"
{if(flag == 1){printf("OR\n");}coluna += yyleng;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 46 "jucompiler.l"
{if(flag == 1){printf("PLUS\n");}coluna += yyleng;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{if(flag == 1){printf("RBRACE\n");}coluna += yyleng;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{if(flag == 1){printf("RPAR\n");}coluna += yyleng;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{if(flag == 1){printf("RSQ\n");}coluna += yyleng;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 50 "jucompiler.l"
{if(flag == 1){printf("SEMICOLON\n");}coluna += yyleng;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{if(flag == 1){printf("ARROW\n");}coluna += yyleng;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{if(flag == 1){printf("LSHIFT\n");}coluna += yyleng;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{if(flag == 1){printf("RSHIFT\n");}coluna += yyleng;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{if(flag == 1){printf("XOR\n");}coluna += yyleng;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{if(flag == 1){printf("BOOL\n");}coluna += yyleng;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 56 "jucompiler.l"
{if(flag == 1){printf("CLASS\n");}coluna += yyleng;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{if(flag == 1){printf("DOTLENGTH\n");}coluna += yyleng;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 58 "jucompiler.l"
{if(flag == 1){printf("DOUBLE\n");}coluna += yyleng;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 59 "jucompiler.l"
{if(flag == 1){printf("ELSE\n");}coluna += yyleng;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 60 "jucompiler.l"
{if(flag == 1){printf("IF\n");}coluna += yyleng;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{if(flag == 1){printf("INT\n");}coluna += yyleng;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 62 "jucompiler.l"
{if(flag == 1){printf("PRINT\n");}coluna += yyleng;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 63 "jucompiler.l"
{if(flag == 1){printf("PARSEINT\n");}coluna += yyleng;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 64 "jucompiler.l"
{if(flag == 1){printf("PUBLIC\n");}coluna += yyleng;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{if(flag == 1){printf("RETURN\n");}coluna += yyleng;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{if(flag == 1){printf("STATIC\n");}coluna += yyleng;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{if(flag == 1){printf("STRING\n");}coluna += yyleng;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{if(flag == 1){printf("VOID\n");}coluna += yyleng;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{if(flag == 1){printf("WHILE\n");}coluna += yyleng;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{if(flag == 1){printf("ID(%s)\n", yytext);}coluna += yyleng;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 74 "jucompiler.l"
{if(flag == 1){printf("REALLIT(%s)\n", yytext);}coluna += yyleng;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{if(flag == 1){printf("INTLIT(%s)\n", yytext);}coluna += yyleng;}             
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{BEGIN SINGLE_LINE_COMMENT;coluna += yyleng;}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 80 "jucompiler.l"
{BEGIN 0;coluna = 1; yylineno++;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{;coluna += yyleng;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{linha_aux = yylineno;coluna_aux=coluna;coluna += 2;BEGIN(COMMENT);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{BEGIN(0);coluna += yyleng;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 88 "jucompiler.l"
{yylineno++;coluna = 1;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 89 "jucompiler.l"
{printf("Line %d, col %d: unterminated comment\n", linha_aux, coluna_aux); BEGIN(0);coluna += yyleng;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{BEGIN(STRLIT);bzero(buffer,sizeof(buffer));linha_aux=yylineno;coluna_aux=coluna;coluna++;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{if(flag == 1){printf("STRLIT(\"%s\")\n",buffer);}BEGIN(0);bzero(buffer,sizeof(buffer));coluna+=yyleng;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{if ((yytext[1] != '\r') && (yytext[1] != '\n')) {printf("Line %d, col %d: invalid escape sequence (%s)\n", yylineno, coluna, yytext);} else {printf("Line %d, col %d: invalid escape sequence (\\)\n", yylineno, coluna);}BEGIN ERRO_STRLIT;coluna+=yyleng;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{strcat(buffer,&yytext[0]);coluna+=yyleng;}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 98 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (\\)\n", yylineno, coluna); printf("Line %d, col %d: unterminated string literal\n", linha_aux, coluna_aux);coluna = 1; yylineno++; bzero(buffer,sizeof(buffer)); BEGIN(0);}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 99 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n", linha_aux, coluna_aux); BEGIN(0);bzero(buffer,sizeof(buffer)); yylineno++; coluna = 1;}
	YY_BREAK
case YY_STATE_EOF(STRLIT):
#line 100 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n", linha_aux, coluna_aux); BEGIN(0);bzero(buffer,sizeof(buffer)); yylineno++; coluna = 1;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{strcat(buffer,&yytext[0]);coluna+=yyleng;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{BEGIN (0);coluna+=yyleng;coluna+=yyleng;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{if ((yytext[1] != '\r') && (yytext[1] != '\n')) {printf("Line %d, col %d: invalid escape sequence (%s)\n", yylineno, coluna, yytext);} else {printf("Line %d, col %d: invalid escape sequence (\\)\n", yylineno, coluna);}BEGIN ERRO_STRLIT;coluna+=yyleng;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{strcat(buffer,&yytext[0]);coluna+=yyleng;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{strcat(buffer,&yytext[0]);coluna+=yyleng;}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 108 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n", linha_aux, coluna_aux); BEGIN(0);bzero(buffer,sizeof(buffer)); yylineno++; coluna = 1;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{coluna+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(ERRO_STRLIT):
#line 110 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n", linha_aux, coluna_aux); BEGIN(0);bzero(buffer,sizeof(buffer)); yylineno++; coluna = 1;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 116 "jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 117 "jucompiler.l"
{yylineno++;coluna = 1;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n",yylineno,coluna, yytext);coluna += yyleng;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 121 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1379 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLE_LINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 374 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 374 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 373);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 121 "jucompiler.l"


int main(int argc, char *argv[]){
    if(argc > 1){
		if(strcmp(argv[1],"-e1") == 0){
			flag=0;
		}
	}   
    yylex();
    return 0;
}

int yywrap() {
    return 1;
}
