
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[385] =
    {   0,
        0,    0,    0,    0,   57,   57,    0,    0,   71,   69,
       66,   68,   68,   67,   19,   56,   45,   17,   69,   13,
       23,    5,   21,    6,   16,   69,    7,   47,   47,   25,
       15,    4,   10,   45,   45,   14,   24,   29,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   11,   69,   22,   55,   54,
       54,   55,   57,   65,   63,   64,   50,   49,   49,   68,
       18,   45,    3,    1,   26,   46,    0,    0,   51,   48,
       46,    0,    0,    0,   47,    0,   27,   12,    8,    9,
       28,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,    1,   45,   45,   45,
       45,   45,   45,   45,   45,   35,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   20,   54,   53,    0,   52,
       57,   64,   62,   58,   59,   61,   60,    0,   46,    0,
       46,    0,    0,   46,    0,   47,   45,   45,   45,   46,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
        1,   45,   45,   45,   36,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,    0,   46,    0,    0,
        0,    0,   46,   46,   46,    0,    0,    0,   45,   45,
       45,    0,    0,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   34,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,    2,   43,
       45,   45,   46,   46,    0,   46,    0,    0,   46,   46,
       46,   46,    0,   47,   45,   45,   45,    0,   46,   45,
       45,   45,   45,   45,   31,   45,   45,   45,   45,    1,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,    1,   45,   45,   44,   46,   46,
        0,   46,   46,   46,   46,   45,   42,    1,   46,   46,
       45,   45,   45,   45,   33,   45,   45,   45,   45,   45,
       45,   45,   45,   39,   40,   41,   45,   45,   45,   45,
       32,    1,    0,   45,   30,   45,   45,   45,   45,   45,
       45,   45,   45,   45,    0,    0,   45,   45,   45,   45,
       45,   45,    0,    0,   45,   45,   45,    0,    0,   45,
        0,    0,   45,    0,    0,    0,    0,    0,    0,    0,
        0,   38,   37,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   26,   44,   45,   46,   47,
       48,   49,   26,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    1,    4,    4,    4,    4,    1,
        3,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[392] =
    {   0,
        0,    0,   59,   60,   63,   64,   65,   72,  615,  616,
      616,  616,  611,  616,  589,  616,    0,  616,  601,  616,
      616,  616,  596,  616,   59,   58,   66,   70,   78,  616,
       58,  586,   62,  562,   49,  616,  616,  616,   87,   64,
       63,   81,   54,   77,   92,  560,   85,  559,   75,   95,
      567,   94,   92,  557,  562,  616,  543,  616,  616,  616,
      599,  124,    0,  616,  616,  110,  616,  616,  616,  616,
      616,    0,  616,  616,  616,  132,  134,  562,  616,  616,
      143,  154,  163,  165,  169,  171,  616,  616,  616,  616,
      616,  548,  549,  547,  177,  180,  546,  545,  547,  555,

      541,  155,  557,  556,  543,  549,  535,  536,  533,  533,
      539,  536,  534,  531,  528,    0,  530,  158,  531,  525,
      521,  530,  537,   96,  537,  520,  523,  123,  521,  526,
      521,  126,  167,  122,  524,  616,  616,  616,  142,  616,
        0,  616,  616,  616,  616,  616,  616,  198,  201,  519,
      205,  216,  209,  221,  225,  229,  526,  521,  511,  233,
      254,  245,  510,  522,  515,  524,  519,  518,  519,  505,
      503,  206,  518,  516,  512,  504,  510,  497,  512,  511,
        0,  497,  203,  492,  504,  501,  498,  495,  495,  484,
      485,  491,  482,  484,  481,  489,  492,  478,  492,  477,

      479,  479,  486,  486,  488,  477,  241,  256,  263,  480,
      271,  261,  273,  275,  277,  284,  282,  292,  479,  472,
      479,  300,  298,  302,  307,  467,  466,  476,  470,  471,
      461,  459,  467,  456,  463,    0,  460,  467,  460,  452,
      464,  452,  466,  450,  445,  463,  462,  457,  452,  444,
      441,  449,  454,  440,  452,  446,  432,  435,    0,    0,
      433,  445,  309,  311,  313,  317,  431,  319,  326,  328,
      332,  334,  338,  343,  443,  440,  434,  349,  353,  355,
      358,  444,  426,  442,    0,  429,  430,  435,  435,  427,
      425,  418,  422,  428,  428,  425,  413,  427,  426,  415,

      424,  408,  417,  408,  406,  413,  412,    0,  360,  362,
      412,  364,  370,  379,  381,  403,    0,  434,  385,  387,
      414,  403,  396,  396,    0,  396,  389,  404,  403,  404,
      396,  381,  366,    0,    0,    0,  377,  368,  375,  367,
      616,  393,  362,  357,    0,  364,  350,  356,  356,  349,
      337,  324,  320,  326,  308,  297,  292,  294,  296,  286,
      271,  258,  273,  254,  249,  249,  229,  235,  255,  231,
      187,  185,  189,  184,  167,  184,  151,  132,   72,   37,
       31,  616,  616,  616,  421,  425,  429,   65,  433,  437,
      441

    } ;

static const flex_int16_t yy_def[392] =
    {   0,
      384,    1,  385,  385,  386,  386,  387,  387,  384,  384,
      384,  384,  384,  384,  384,  384,  388,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  388,  388,  384,  384,  384,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  384,  384,  384,  384,  384,
      384,  389,  390,  384,  384,  391,  384,  384,  384,  384,
      384,  388,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  388,  388,  388,  388,  388,  388,  388,  388,  388,

      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  384,  384,  384,  389,  384,
      390,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  388,  388,  388,  384,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,

      388,  388,  388,  388,  388,  388,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  388,  388,
      388,  384,  384,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  388,  388,  388,  384,  384,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,

      388,  388,  388,  388,  388,  388,  388,  388,  384,  384,
      384,  384,  384,  384,  384,  388,  388,  388,  384,  384,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      384,  388,  384,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  384,  384,  388,  388,  388,  388,
      388,  388,  384,  384,  388,  388,  388,  384,  384,  388,
      384,  384,  388,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,    0,  384,  384,  384,  384,  384,  384,
      384

    } ;

static const flex_int16_t yy_nxt[678] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   17,   17,   34,   35,   36,
       10,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   17,   47,   17,   48,   17,   49,   17,   50,   51,
       52,   53,   17,   54,   55,   17,   17,   17,   56,   57,
       58,   60,   60,   61,   61,   64,   64,   68,   72,   69,
       65,   65,   62,   62,   68,   74,   69,   76,   76,   79,
       87,   88,  383,   75,   80,   90,   91,   81,  382,   82,
       82,   77,  106,   66,   66,   81,   83,   85,   85,   97,

       93,  107,   78,   84,   83,   94,   95,   95,   83,  120,
       99,   86,  100,  121,   98,  102,   83,  143,  381,  101,
       96,  108,  103,  109,  116,  104,  111,  122,  105,  123,
      117,  118,  110,  132,  112,  127,  113,  139,  190,  114,
      143,  133,  140,  191,  124,  128,  129,  125,  130,  144,
      131,   76,   76,  149,  149,  139,  145,  195,  148,  146,
      384,  147,  151,  151,  204,   77,  205,   77,  200,  152,
      148,   81,  196,   82,   82,  201,   77,  153,  380,  153,
       83,  152,  154,  154,  155,  155,   81,   84,   85,   85,
      156,  156,   83,  379,  160,   83,   95,   95,   84,   95,

       95,  202,   86,  161,   86,  168,  169,   83,  184,  185,
      162,  378,  207,   96,  207,  161,  377,  208,  208,  203,
      149,  149,  376,  181,  151,  151,  181,  209,  154,  154,
      212,  211,  212,  375,   77,  213,  213,  374,   77,  209,
      214,  214,  160,  211,  155,  155,  160,  241,  156,  156,
      242,  216,  149,  149,  215,  216,  232,  233,  217,  222,
      208,  208,  218,  216,  225,  225,   77,  216,  223,  373,
      223,  222,  372,  224,  224,  263,  263,  265,  162,  265,
      213,  213,  266,  266,  371,  268,  370,  268,  181,  264,
      269,  269,  270,  270,  214,  214,  215,  215,  223,  181,

      223,  273,  273,  272,  272,  369,  271,  368,  215,  181,
      215,  274,  274,  367,  278,  217,  278,  272,  272,  279,
      279,  280,  280,  181,  160,  218,  225,  225,  263,  263,
      264,  264,  266,  266,  181,  281,  309,  309,  269,  269,
      162,  366,  264,  365,  264,  312,  312,  270,  270,  364,
      310,  271,  271,  314,  314,  160,  363,  273,  273,  313,
      160,  271,  274,  274,  181,  271,  362,  315,  279,  279,
      361,  217,  319,  319,  280,  280,  218,  281,  281,  309,
      309,  310,  310,  312,  312,  181,  320,  360,  281,  313,
      313,  281,  359,  310,  358,  310,  357,  313,  314,  314,

      315,  315,  181,  313,  319,  319,  320,  320,  181,  356,
      355,  354,  315,  353,  315,  352,  351,  350,  320,  181,
      320,   59,   59,   59,   59,   63,   63,   63,   63,   67,
       67,   67,   67,  138,  181,  138,  138,  141,  349,  348,
      141,  142,  347,  142,  142,  181,  181,  181,  346,  345,
      344,  343,  342,  341,  340,  339,  181,  338,  181,  337,
      336,  335,  334,  333,  332,  331,  181,  330,  329,  181,
      328,  327,  326,  325,  324,  323,  322,  181,  321,  318,
      317,  316,  311,  308,  307,  306,  305,  304,  303,  181,
      302,  301,  181,  300,  299,  298,  297,  296,  295,  294,

      293,  292,  291,  181,  290,  259,  289,  288,  287,  286,
      181,  285,  181,  181,  284,  283,  282,  277,  276,  275,
      267,  262,  261,  260,  259,  258,  257,  181,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  181,
      245,  181,  244,  243,  181,  240,  239,  238,  237,  181,
      236,  235,  234,  231,  181,  230,  181,  181,  229,  228,
      227,  226,  221,  220,  219,  210,  206,  199,  198,  197,
      194,  193,  192,  189,  188,  181,  187,  186,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  167,  166,  165,  164,  163,  159,  158,  157,

      150,  137,  136,  135,  134,  126,  119,  115,   92,   89,
       74,   73,   71,   70,  384,    9,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384
    } ;

static const flex_int16_t yy_chk[678] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    3,    4,    5,    6,    7,  388,    7,
        5,    6,    3,    4,    8,   25,    8,   26,   26,   27,
       31,   31,  381,   25,   27,   33,   33,   28,  380,   28,
       28,   26,   43,    5,    6,   29,   28,   29,   29,   40,

       35,   43,   26,   28,   29,   35,   39,   39,   28,   49,
       41,   29,   41,   49,   40,   42,   29,   66,  379,   41,
       39,   44,   42,   44,   47,   42,   45,   49,   42,   50,
       47,   47,   44,   53,   45,   52,   45,   62,  124,   45,
       66,   53,   62,  124,   50,   52,   52,   50,   52,   66,
       52,   76,   76,   77,   77,  139,   66,  128,   76,   66,
      139,   66,   81,   81,  134,   76,  134,   77,  132,   81,
       76,   82,  128,   82,   82,  132,   81,   83,  378,   83,
       82,   81,   83,   83,   84,   84,   85,   82,   85,   85,
       86,   86,   82,  377,   95,   85,   95,   95,   84,   96,

       96,  133,   85,   95,   86,  102,  102,   85,  118,  118,
       95,  376,  148,   96,  148,   95,  375,  148,  148,  133,
      149,  149,  374,  133,  151,  151,  373,  149,  153,  153,
      152,  151,  152,  372,  149,  152,  152,  371,  151,  149,
      154,  154,  155,  151,  155,  155,  156,  183,  156,  156,
      183,  155,  160,  160,  154,  156,  172,  172,  155,  160,
      207,  207,  156,  155,  162,  162,  160,  156,  161,  370,
      161,  160,  369,  161,  161,  208,  208,  209,  162,  209,
      212,  212,  209,  209,  368,  211,  367,  211,  366,  208,
      211,  211,  213,  213,  214,  214,  215,  215,  216,  365,

      216,  217,  217,  216,  216,  364,  213,  363,  214,  362,
      215,  218,  218,  361,  222,  217,  222,  223,  223,  222,
      222,  224,  224,  360,  225,  218,  225,  225,  263,  263,
      264,  264,  265,  265,  359,  224,  266,  266,  268,  268,
      225,  358,  263,  357,  264,  269,  269,  270,  270,  356,
      266,  271,  271,  272,  272,  273,  355,  273,  273,  269,
      274,  270,  274,  274,  354,  271,  353,  272,  278,  278,
      352,  273,  279,  279,  280,  280,  274,  281,  281,  309,
      309,  310,  310,  312,  312,  351,  279,  350,  280,  313,
      313,  281,  349,  309,  348,  310,  347,  312,  314,  314,

      315,  315,  346,  313,  319,  319,  320,  320,  344,  343,
      342,  340,  314,  339,  315,  338,  337,  333,  319,  332,
      320,  385,  385,  385,  385,  386,  386,  386,  386,  387,
      387,  387,  387,  389,  331,  389,  389,  390,  330,  329,
      390,  391,  328,  391,  391,  327,  326,  324,  323,  322,
      321,  318,  316,  311,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  284,  283,  282,  277,
      276,  275,  267,  262,  261,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,

      243,  242,  241,  240,  239,  238,  237,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  221,  220,  219,
      210,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  182,  180,  179,  178,  177,  176,
      175,  174,  173,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  159,  158,  157,  150,  135,  131,  130,  129,
      127,  126,  125,  123,  122,  121,  120,  119,  117,  115,
      114,  113,  112,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  101,  100,   99,   98,   97,   94,   93,   92,

       78,   61,   57,   55,   54,   51,   48,   46,   34,   32,
       23,   19,   15,   13,    9,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../Meta1/jucompiler.l"
/*
    Autores
Gonçalo Neves 2020239361
Gonçalo Ferreira 2020226867
*/
#line 9 "../Meta1/jucompiler.l"
    #include "y.tab.h"

    int coluna = 1;
    int linha_aux = 0;
    int coluna_aux = 0;
    char buffer[1024];

    int flag = 1;
    int error = 0;

#line 736 "lex.yy.c"

#line 738 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRLIT 2
#define SINGLE_LINE_COMMENT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 34 "../Meta1/jucompiler.l"


#line 961 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 385 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 616 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "../Meta1/jucompiler.l"
{if(flag == 1){printf("RESERVED(%s)\n", yytext);}coluna += yyleng;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "../Meta1/jucompiler.l"
{if(flag == 1){printf("BOOLLIT(%s)\n", yytext);}coluna += yyleng;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "../Meta1/jucompiler.l"
{if(flag == 1){printf("AND\n");}coluna += yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "../Meta1/jucompiler.l"
{if(flag == 1){printf("ASSIGN\n");}coluna += yyleng;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "../Meta1/jucompiler.l"
{if(flag == 1){printf("STAR\n");}coluna += yyleng;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "../Meta1/jucompiler.l"
{if(flag == 1){printf("COMMA\n");}coluna += yyleng;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "../Meta1/jucompiler.l"
{if(flag == 1){printf("DIV\n");}coluna += yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "../Meta1/jucompiler.l"
{if(flag == 1){printf("EQ\n");}coluna += yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "../Meta1/jucompiler.l"
{if(flag == 1){printf("GE\n");}coluna += yyleng;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "../Meta1/jucompiler.l"
{if(flag == 1){printf("GT\n");}coluna += yyleng;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "../Meta1/jucompiler.l"
{if(flag == 1){printf("LBRACE\n");}coluna += yyleng;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 48 "../Meta1/jucompiler.l"
{if(flag == 1){printf("LE\n");}coluna += yyleng;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 49 "../Meta1/jucompiler.l"
{if(flag == 1){printf("LPAR\n");}coluna += yyleng;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "../Meta1/jucompiler.l"
{if(flag == 1){printf("LSQ\n");}coluna += yyleng;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 51 "../Meta1/jucompiler.l"
{if(flag == 1){printf("LT\n");}coluna += yyleng;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 52 "../Meta1/jucompiler.l"
{if(flag == 1){printf("MINUS\n");}coluna += yyleng;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 53 "../Meta1/jucompiler.l"
{if(flag == 1){printf("MOD\n");}coluna += yyleng;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 54 "../Meta1/jucompiler.l"
{if(flag == 1){printf("NE\n");}coluna += yyleng;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "../Meta1/jucompiler.l"
{if(flag == 1){printf("NOT\n");}coluna += yyleng;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "../Meta1/jucompiler.l"
{if(flag == 1){printf("OR\n");}coluna += yyleng;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "../Meta1/jucompiler.l"
{if(flag == 1){printf("PLUS\n");}coluna += yyleng;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "../Meta1/jucompiler.l"
{if(flag == 1){printf("RBRACE\n");}coluna += yyleng;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "../Meta1/jucompiler.l"
{if(flag == 1){printf("RPAR\n");}coluna += yyleng;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "../Meta1/jucompiler.l"
{if(flag == 1){printf("RSQ\n");}coluna += yyleng;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "../Meta1/jucompiler.l"
{if(flag == 1){printf("SEMICOLON\n");}coluna += yyleng;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "../Meta1/jucompiler.l"
{if(flag == 1){printf("ARROW\n");}coluna += yyleng;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "../Meta1/jucompiler.l"
{if(flag == 1){printf("LSHIFT\n");}coluna += yyleng;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "../Meta1/jucompiler.l"
{if(flag == 1){printf("RSHIFT\n");}coluna += yyleng;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "../Meta1/jucompiler.l"
{if(flag == 1){printf("XOR\n");}coluna += yyleng;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 66 "../Meta1/jucompiler.l"
{if(flag == 1){printf("BOOL\n");}coluna += yyleng;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 67 "../Meta1/jucompiler.l"
{if(flag == 1){printf("CLASS\n");}coluna += yyleng;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 68 "../Meta1/jucompiler.l"
{if(flag == 1){printf("DOTLENGTH\n");}coluna += yyleng;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 69 "../Meta1/jucompiler.l"
{if(flag == 1){printf("DOUBLE\n");}coluna += yyleng;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 70 "../Meta1/jucompiler.l"
{if(flag == 1){printf("ELSE\n");}coluna += yyleng;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "../Meta1/jucompiler.l"
{if(flag == 1){printf("IF\n");}coluna += yyleng;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 72 "../Meta1/jucompiler.l"
{if(flag == 1){printf("INT\n");}coluna += yyleng;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 73 "../Meta1/jucompiler.l"
{if(flag == 1){printf("PRINT\n");}coluna += yyleng;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 74 "../Meta1/jucompiler.l"
{if(flag == 1){printf("PARSEINT\n");}coluna += yyleng;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "../Meta1/jucompiler.l"
{if(flag == 1){printf("PUBLIC\n");}coluna += yyleng;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "../Meta1/jucompiler.l"
{if(flag == 1){printf("RETURN\n");}coluna += yyleng;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "../Meta1/jucompiler.l"
{if(flag == 1){printf("STATIC\n");}coluna += yyleng;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "../Meta1/jucompiler.l"
{if(flag == 1){printf("STRING\n");}coluna += yyleng;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "../Meta1/jucompiler.l"
{if(flag == 1){printf("VOID\n");}coluna += yyleng;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "../Meta1/jucompiler.l"
{if(flag == 1){printf("WHILE\n");}coluna += yyleng;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "../Meta1/jucompiler.l"
{if(flag == 1){printf("ID(%s)\n", yytext);}coluna += yyleng;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "../Meta1/jucompiler.l"
{if(flag == 1){printf("REALLIT(%s)\n", yytext);}coluna += yyleng;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "../Meta1/jucompiler.l"
{if(flag == 1){printf("INTLIT(%s)\n", yytext);}coluna += yyleng; yylval.intlit = atoi(yytext); return INTLIT;}             
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "../Meta1/jucompiler.l"
{BEGIN SINGLE_LINE_COMMENT;coluna += yyleng;}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 91 "../Meta1/jucompiler.l"
{BEGIN 0;coluna = 1; yylineno++;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "../Meta1/jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 96 "../Meta1/jucompiler.l"
{linha_aux = yylineno;coluna_aux=coluna;coluna += 2;BEGIN(COMMENT);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 97 "../Meta1/jucompiler.l"
{BEGIN(0);coluna += yyleng;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 98 "../Meta1/jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 99 "../Meta1/jucompiler.l"
{yylineno++;coluna = 1;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 100 "../Meta1/jucompiler.l"
{printf("Line %d, col %d: unterminated comment\n", linha_aux, coluna_aux); BEGIN(0);coluna += yyleng;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 101 "../Meta1/jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 103 "../Meta1/jucompiler.l"
{coluna_aux = coluna; coluna += 1; linha_aux=yylineno; BEGIN STRLIT; buffer[0] = '\0'; error = 0;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 104 "../Meta1/jucompiler.l"
{coluna+=yyleng; strcat(buffer, yytext);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 105 "../Meta1/jucompiler.l"
{coluna+=yyleng; strcat(buffer, yytext);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 106 "../Meta1/jucompiler.l"
{coluna+=yyleng; strcat(buffer, yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 107 "../Meta1/jucompiler.l"
{coluna+=yyleng; strcat(buffer, yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 108 "../Meta1/jucompiler.l"
{coluna+=yyleng; strcat(buffer, yytext);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 109 "../Meta1/jucompiler.l"
{coluna+=yyleng; strcat(buffer, yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 110 "../Meta1/jucompiler.l"
{coluna+=yyleng; BEGIN 0;
                             if (error!=1){if(flag==1){printf("STRLIT(\"%s\")\n", buffer);}}}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 112 "../Meta1/jucompiler.l"
{error=1; if (yytext[1] != '\r') {printf("Line %d, col %d: invalid escape sequence (%s)\n", yylineno, coluna, yytext); coluna+=yyleng;} else {printf("Line %d, col %d: invalid escape sequence (\\)\n", yylineno, coluna); coluna+=yyleng;}}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 113 "../Meta1/jucompiler.l"
{error=1; printf("Line %d, col %d: unterminated string literal\n", linha_aux, coluna_aux); yylineno++; coluna=1; coluna_aux=0; BEGIN 0;}
	YY_BREAK
case YY_STATE_EOF(STRLIT):
#line 114 "../Meta1/jucompiler.l"
{error=1; printf("Line %d, col %d: unterminated string literal\n", linha_aux, coluna_aux); yylineno++; coluna=1; coluna_aux=0; BEGIN 0;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 116 "../Meta1/jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 117 "../Meta1/jucompiler.l"
{coluna += yyleng;}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 118 "../Meta1/jucompiler.l"
{yylineno++;coluna = 1;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 119 "../Meta1/jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n",yylineno,coluna, yytext);coluna += yyleng;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 122 "../Meta1/jucompiler.l"
ECHO;
	YY_BREAK
#line 1381 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLE_LINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 385 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 385 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 384);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 122 "../Meta1/jucompiler.l"


int main(int argc, char *argv[]){
    if(argc > 1){
		if(strcmp(argv[1],"-e1") == 0){
			flag=0;
		}
	}   
    yylex();
    return 0;
}

int yywrap() {
    return 1;
}

void yyerror (char *s)
{
printf ("%s\n", s);
}
